services:
  - type: web
    name: diogo-live
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_HANDLE
        value: "@FulLShoT"